### PR TITLE
#1987 Switch rules synchronization using H&S approach.

### PR DESCRIPTION
**Pull request by dpoltavets**
- implemented switch rules synchronization in WFM;
- eliminated topology engine.

Closes: #1987.

---
This change is [Reviewable](https://reviewable.io/reviews/telstra/open-kilda/2009)

### CODE REVIEW

**Comment by dpoltavets** [comment]
___
*[services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SyncRulesServiceImpl.java, line 59 at r3](https://reviewable.io/reviews/telstra/open-kilda/2009#-LYblPG7-46--63l1C4T:-LYePTz1C8EnnNSoc2C6:bss4a2b) ([raw file](https://github.com/telstra/open-kilda/blob/187c4e556517a52b6f3cc9b92f6f79e9bd281015/services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SyncRulesServiceImpl.java#L59)):*
<details><summary><i>Previously, nikitamarchenko (Nikita Marchenko) wrote…</i></summary><blockquote>

that only for testing!
</blockquote></details>

Removed.

**Comment by dpoltavets** [comment]
*[a discussion](https://reviewable.io/reviews/telstra/open-kilda/2009#-LYl-OIa2qRkK-IrykYr:-LYlKh5FB1J5ojilIHsf:biqupjd) (no related file):*
<details><summary><i>Previously, nikitamarchenko (Nikita Marchenko) wrote…</i></summary><blockquote>

overall is good but tests are missing
</blockquote></details>

Tests was added.

---

**Comment by dpoltavets** [comment]
___
*[services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchSyncRulesCarrier.java, line 27 at r7](https://reviewable.io/reviews/telstra/open-kilda/2009#-LZ9k-Xv-I8-3Xonyck7:-LZ9uQ51BufotroeWaru:b-896fix) ([raw file](https://github.com/telstra/open-kilda/blob/cd3ae5170f82ca2f1d34647bb67317692d7cf599/services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchSyncRulesCarrier.java#L27)):*
<details><summary><i>Previously, nikitamarchenko (Nikita Marchenko) wrote…</i></summary><blockquote>

Move manager to a constructor of SyncRulesService.
</blockquote></details>

Done.

**Comment by nikitamarchenko** [comment]
Need additional approve from @rtretyak.

**Comment by rtretyak** [comment]
Tested on stage, was able to successfully sync ingress/egress/transit flow rules with/without meters on noviflow/centec/accton switches.

**Pull request merged**
