### PR TITLE
Update logic to exclude redundant sub flows from diversity section

### LINKED ISSUE #5181: Y flow get paths API should not return sub flows of the same Y flow in diversity group section
**Steps to reproduce:**
1. Create a Y flow via `POST /v2/y-flows`

```
{
  "y_flow_id": "flow_1",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "9"
  },
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
  "sub_flows": [
    {
      "flow_id": "sub_1",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 123
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 456
      }
    },
{
      "flow_id": "sub_2",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 345
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 789
      }
    }
  ]
}
```

2. Create another Y flow with diversity to `flow_1` via `POST /v2/y-flows`
```
{
  "y_flow_id": "flow_2",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "8"
  },
""diverse_flow_id": "flow_1"",
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
  "sub_flows": [
    {
      "flow_id": "sub_3",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "3",
        "vlan_id": 111
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 222
      }
    },
{
      "flow_id": "sub_4",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "3",
        "vlan_id": 333
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 444
      }
    }
  ]
}
```

3. Get paths of both flows via `GET /v2/y-flows/{y_flow_id}/paths`

**Expected result:**
Each subflow must contain 2 subflows in diverse group section (these 2 subflows are subflows of diversity Y flow)
Diverse grpup section must NOT contain subflows of the current flow.
Expected responses are:
`flow_1`

```
{
******
  "sub_flow_paths":[
  {
    "flow_id":"sub_1",
    ******
    "diverse_group":{
    "other_flows":[
   { 
      "flowid":"sub_4",
      ***
   }, 
   {
      "flowid":"sub_3",
     ****
   }
  ]
},
{
    "flow_id":"sub_2",
    *****
    "other_flows":[
    {
       "flowid":"sub_4",
    *****
     }, 
     {
         "flowid":"sub_3",
     *******
     }
    ]
****
 }
```

`flow_2`

```
{
  *****
  "sub_flow_paths":[
    {
      "flow_id":"sub_4",
      *****
      "diverse_group":{
        "other_flows":[
          {
            "flowid":"sub_2",
            *****
          },
          {
            "flowid":"sub_1",
            *****
          }
        ]
      },
    },
    {
      "flow_id":"sub_3",
      "diverse_group":{
        "other_flows":[
          {
            "flowid":"sub_2",
            *****
          },
          {
            "flowid":"sub_1",
            *****
          }
        ]
      },
      *****
    }
  ]
}
```

**Actual result**
`flow_1`

```
{
******
  "sub_flow_paths":[
  {
    "flow_id":"sub_1",
    ******
    "diverse_group":{
    "other_flows":[
   { 
      "flowid":"sub_4",
      ***
   }, 
   {
      "flowid":"sub_3",
     ****
   },
   {
      "flowid":"sub_2",
    ******
    }
  ]
},
{
    "flow_id":"sub_2",
    *****
    "other_flows":[
    {
       "flowid":"sub_4",
    *****
     }, 
     {
         "flowid":"sub_3",
     *******
     },
     {
        "flowid":"sub_1",
        *******
       }
    ]
****
 }
```

`flow_2`

```
{
  *****
  "sub_flow_paths":[
    {
      "flow_id":"sub_4",
      *****
      "diverse_group":{
        "other_flows":[
          {
            "flowid":"sub_3",
            *****
          },
          {
            "flowid":"sub_2",
            *****
          },
          {
            "flowid":"sub_1",
            *****
          }
        ]
      },
    },
    {
      "flow_id":"sub_3",
      "diverse_group":{
        "other_flows":[
          {
            "flowid":"sub_4",
            *****
          },
          {
            "flowid":"sub_2",
            *****
          },
          {
            "flowid":"sub_1",
            *****
          }
        ]
      },
      *****
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by Fedichk**
Closes #5181

### CODE REVIEW

**Review by niksv — APPROVED** [review]

**Comment by pkazlenka** [comment]
@Fedichk , after your changes, response to `/api/v2/y-flows/{y_flow_id}/paths` always has 0-es (but is not null) in `sub_flow_path/*/diverse_group/overlapping_segments`, which is not true.
However, we, probably, should wait for response from Sergei regarding how to calculate overlappings after change in behavior (https://github.com/telstra/open-kilda/issues/5181#issuecomment-1534531595).

**Comment by pkazlenka** [comment]
Verified. There's a minor issue (#5191) which can be fixed separately.

**Review by dmitrii-beliakov — CHANGES_REQUESTED** [review]
Please update unit tests to cover these changes.

**Review by dmitrii-beliakov — APPROVED** [review]
As discussed separately, the test coverage is done [here](https://github.com/telstra/open-kilda/pull/5193), so no need to have tests in this PR

**Pull request merged**
