### PR TITLE
Remove redundant history event creation

### LINKED ISSUE #5320: duplicated update event for in ha-flow history
steps to reproduce

1. create ha flow
2. update ha flow
3. get ha flow history

Actual result: ha flow history contains 2 update entries with the same data 
Expected result: 1 update event in history

### PR DESCRIPTION
**Pull request by dmitrii-beliakov**
This PR fixes creating a history event twice during the HA-flow update.
closes #5320

### CODE REVIEW

**Review by niksv — APPROVED** [review]

**Review by IvanChupin — APPROVED** [review]

**Comment by yuliiamir** [comment]
Ha-Flow status changed from 'In_Progress' to 'Up' in the middle of  updating (both PATCH and PUT operation).
Details: 
flow id: 13Sep174133_338_silverbeet8816
Before update call:  Wednesday, 13 September 2023 17:**41:35**.141
Polling Ha-Flow status by getting link details:
- In progress Wednesday, 13 September 2023 17:**41:35.**845
- UP Wednesday, 13 September 2023 17:**41:36.591** 


      {
        "timestamp": 1694619697.842,
        "timestamp_iso": "2023-09-13T15:**41:37.842Z",** // but flow is in UP status
        "action": "install rules operation was successful",
        "details": "install rules operation was successful. Rules count: 1. Switch id: 00:00:00:00:00:00:00:02"
      }
      
Update details can be found below: 

But, in the history, the updating process is still in progress: 
```
[
  {
    "clazz": "org.openkilda.messaging.payload.history.HaFlowHistoryEntry",
 
     ...
 
  },
  {
    "clazz": "org.openkilda.messaging.payload.history.HaFlowHistoryEntry",
    "ha_flow_id": "13Sep174133_338_silverbeet8816",
    "time": 1694619697.516,
    "timestamp_iso": "2023-09-13T15:41:37.516Z",
    "action": "HA-Flow update",
    "task_id": "48ab232c-4c31-4cc1-90d4-e7dbbd694637 : fn-tests-03a8b0cf-a9c6-4802-bd09-23bdf86f8f59",
    "payloads": [
      {
        "timestamp": 1694619697.516,
        "timestamp_iso": "2023-09-13T15:41:37.516Z",
        "action": "HA-Flow update",
        "details": null
      },
      {
        "timestamp": 1694619697.522,
        "timestamp_iso": "2023-09-13T15:41:37.522Z",
        "action": "HA-flow properties have been updated.",
        "details": null
      },
      {
        "timestamp": 1694619697.619,
        "timestamp_iso": "2023-09-13T15:41:37.619Z",
        "action": "Primary paths have been allocated",
        "details": "The following paths have been allocated for HA-flow 13Sep174133_338_silverbeet8816: forward: 13Sep174133_338_silverbeet8816_edd6d3e4-fcef-4273-b329-742fae98736a, reverse: 13Sep174133_338_silverbeet8816_f613671d-03f4-4712-954c-bc9e2aee9a21"
      },
      {
        "timestamp": 1694619697.842,
        "timestamp_iso": "2023-09-13T15:41:37.842Z",
        "action": "install rules operation was successful",
        "details": "install rules operation was successful. Rules count: 1. Switch id: 00:00:00:00:00:00:00:02"
      },
      {
        "timestamp": 1694619697.852,
        "timestamp_iso": "2023-09-13T15:41:37.852Z",
        "action": "install rules operation was successful",
        "details": "install rules operation was successful. Rules count: 2. Switch id: 00:00:00:00:00:00:00:01"
      },
      {
        "timestamp": 1694619697.877,
        "timestamp_iso": "2023-09-13T15:41:37.877Z",
        "action": "HA-flow was updated with new paths",
        "details": "The HA-flow 13Sep174133_338_silverbeet8816 has been updated with paths 13Sep174133_338_silverbeet8816_edd6d3e4-fcef-4273-b329-742fae98736a / 13Sep174133_338_silverbeet8816_f613671d-03f4-4712-954c-bc9e2aee9a21"
      },
      {
        "timestamp": 1694619698.048,
        "timestamp_iso": "2023-09-13T15:41:38.048Z",
        "action": "install rules operation was successful",
        "details": "install rules operation was successful. Rules count: 7. Switch id: 00:00:00:00:00:00:00:01"
      },
      {
        "timestamp": 1694619698.077,
        "timestamp_iso": "2023-09-13T15:41:38.077Z",
        "action": "install rules operation was successful",
        "details": "install rules operation was successful. Rules count: 4. Switch id: 00:00:00:00:00:00:00:02"
      },
      {
        "timestamp": 1694619698.091,
        "timestamp_iso": "2023-09-13T15:41:38.091Z",
        "action": "HA-flow paths have been installed",
        "details": "The HA-flow paths 13Sep174133_338_silverbeet8816_edd6d3e4-fcef-4273-b329-742fae98736a / 13Sep174133_338_silverbeet8816_f613671d-03f4-4712-954c-bc9e2aee9a21 have been installed"
      },
      {
        "timestamp": 1694619698.135,
        "timestamp_iso": "2023-09-13T15:41:38.135Z",
        "action": "Commands for removing old rules have been sent",
        "details": null
      },
      {
        "timestamp": 1694619698.362,
        "timestamp_iso": "2023-09-13T15:41:38.362Z",
        "action": "remove rules operation was successful",
        "details": "remove rules operation was successful. Rules count: 3. Switch id: 00:00:00:00:00:00:00:02"
      },
      {
        "timestamp": 1694619698.38,
        "timestamp_iso": "2023-09-13T15:41:38.380Z",
        "action": "remove rules operation was successful",
        "details": "remove rules operation was successful. Rules count: 5. Switch id: 00:00:00:00:00:00:00:01"
      },
      {
        "timestamp": 1694619698.419,
        "timestamp_iso": "2023-09-13T15:41:38.419Z",
        "action": "Remove an HA-flow sub path",
        "details": "FlowPath with ID 13Sep174133_338_silverbeet8816_a91fb594-8ab2-4c41-ae22-b76b98bf0616 has been removed"
      },
      {
        "timestamp": 1694619698.44,
        "timestamp_iso": "2023-09-13T15:41:38.440Z",
        "action": "Remove an HA-flow sub path",
        "details": "FlowPath with ID 13Sep174133_338_silverbeet8816_9600fbed-e8ac-4611-bbc9-344ecc1c4de6 has been removed"
      },
      {
        "timestamp": 1694619698.461,
        "timestamp_iso": "2023-09-13T15:41:38.461Z",
        "action": "Remove an HA-flow sub path",
        "details": "FlowPath with ID 13Sep174133_338_silverbeet8816_9b2e91b0-2bb8-4d64-b30d-7347aa417b5f has been removed"
      },
      {
        "timestamp": 1694619698.481,
        "timestamp_iso": "2023-09-13T15:41:38.481Z",
        "action": "Remove an HA-flow sub path",
        "details": "FlowPath with ID 13Sep174133_338_silverbeet8816_eecf19d1-8b11-4f11-ad53-dc93dde65929 has been removed"
      },
      {
        "timestamp": 1694619698.497,
        "timestamp_iso": "2023-09-13T15:41:38.497Z",
        "action": "Remove an HA-flow path",
        "details": "HaFlowPath with ID 13Sep174133_338_silverbeet8816_4ab7a789-766b-486d-b4fc-d8c99145c666 has been removed"
      },
      {
        "timestamp": 1694619698.506,
        "timestamp_iso": "2023-09-13T15:41:38.506Z",
        "action": "Remove an HA-flow path",
        "details": "HaFlowPath with ID 13Sep174133_338_silverbeet8816_e8e4d968-6d7e-407a-89cd-a31cc0a1fac1 has been removed"
      },
      {
        "timestamp": 1694619698.531,
        "timestamp_iso": "2023-09-13T15:41:38.531Z",
        "action": "Ha-flow resources have been deallocated",
        "details": "The ha-flow resources for 13Sep174133_338_silverbeet8816_4ab7a789-766b-486d-b4fc-d8c99145c666 / 13Sep174133_338_silverbeet8816_e8e4d968-6d7e-407a-89cd-a31cc0a1fac1 have been deallocated"
      },
      {
        "timestamp": 1694619698.573,
        "timestamp_iso": "2023-09-13T15:41:38.573Z",
        "action": "The HA-flow status has been set to UP",
        "details": null
      }
    ],
    "dumps": [
      {
        "task_id": "48ab232c-4c31-4cc1-90d4-e7dbbd694637 : fn-tests-03a8b0cf-a9c6-4802-bd09-23bdf86f8f59",
       ...
      }
    ],
    "timestamp": 1694623166085
  },
  {
    "clazz": "org.openkilda.messaging.payload.history.HaFlowHistoryEntry",
    "ha_flow_id": "13Sep174133_338_silverbeet8816",
    "time": 1694619699.586,
    "timestamp_iso": "2023-09-13T15:41:39.586Z",
    "action": "HA-Flow delete",
   ...
  }
]
```

**Comment by dmitrii-beliakov** [comment]
points 1 and 2 about the HA flow partial update are addressed in another PR [here](https://github.com/telstra/open-kilda/pull/5340)

**Comment by yuliiamir** [comment]
The issue has been fixed in the scope of https://github.com/telstra/open-kilda/pull/5340
and the appropriate tests have been updated in the scope of https://github.com/telstra/open-kilda/pull/5374

**Comment by dmitrii-beliakov** [comment]
Fixed and will be delivered in the scope of another issue.

**Pull request closed without merging**
