### PR TITLE
fix QR code image display issue in 2FA screen

### PR DESCRIPTION
**Pull request by gauravchug**
Resolves: #5703

### CODE REVIEW

**Comment by IvanChupin** [comment]
image
image
image
image
image

Hey Gaurav, @gauravchug. 
FYI 
The login page is broken.

**Comment by gauravchug** [comment]
I removed the static location for resources added to resolve static resource path issues in the IDE.

**Comment by IvanChupin** [comment]
problem has been resolved.
image

Interesting story regarding tabs in make.
https://beebo.org/haycorn/2015-04-20_tabs-and-makefiles.html

**Comment by yuliiamir** [comment]
Verified that a new user can log in to the system with 2FA (code was successfully added through Google Authenticator /Microsoft Authenticator+)

**Pull request merged**
